name: testingpost
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgrace
  postgrace:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: testing
      PGDATA: /var/Lib/postgresql/18/docker
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
